# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               "Seamus' blog"
tagline:             "A Fantastic Blog"
description:         "A friendly blog by me"


# About/contact
author:              "Seamus Lloyd White"
  name:              "Seamus Lloyd White"
 

# Custom vars
version:             2.0

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu
