# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Seamus Lloyd White
tagline:             'A mind blowing blog'
description:         'A fantastic blog by me'
url:                 http://seamuslloydwhite.github.io
baseurl:             /
paginate:            7

# About/contact
author:              Seamus Lloyd White
  name:              Seamus Lloyd White
  url:               
  email:             

# Custom vars
version:             2.0

# Social Media
github:				https://github.com/Seamuslloydwhite
twitter:			
disqus:       

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu
