# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# Setup
title:               Seamus LW
tagline:             'Great stuff'
description:         'A great blog about IT'
url:                 http://seamuslloydwhite.github.io
baseurl:             /
paginate:            7

# About/contact
author:    seamuslloydwhite         
name:    seamuslloydwhite          
url:     seamuslloydwhite.github.io          
email:   seamus.lloydwhite@challoners.org          

# Custom vars
version:     2.0
  
# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu
